### ISSUE TITLE
自定义图层闪动问题

### ISSUE THREAD

**Issue by altermancdx** [FreeGIS/mapboxgl-customelayer#1]
你好，我看了官网 和 你在hello_triangle demo里，都有一个问题，当地图zoom增加时，三角形会开始 闪烁，这个问题困扰我很久，不清楚为何会出现这个问题，以及怎么解决这个问题，

**Comment by altermancdx** [comment]
自问自答一下吧，JavaScript使用的是8字节双精度数值类型， 而webgl中最高只能支持4字节的精度类型，其有效位最多只有7位。当地图放大时超出其有效位范围，导致的渲染中的闪动问题。解决方法可以参考官网的另一个案例，这个案例中的模型能正常渲染，是因为模型的顶点信息，都是相对于其中心点的坐标。

**Comment by FreeGIS** [comment]
谢谢，麻烦告诉我哪个例子吗？其实arcgis他们也是中心点去算的。。。但是其实也会有抖动。。。

**Comment by FreeGIS** [comment]
> h

谢谢，麻烦告诉我哪个例子吗？其实arcgis他们也是中心点去算的。。。但是其实也会有抖动。。。

**Comment by FreeGIS** [comment]
谢谢，麻烦告诉我哪个例子吗？其实arcgis他们也是中心点去算的。。。但是其实也会有抖动。。。
